### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by victorycomrades** [Peiyang-Aeromodelling-Association/demo-repository#21]
### 请确认你已经完成了以下检查

- [X] 有没有查找过以前类似的问题？
- [X] 有没有上网查过？
- [X] 有没有尝试独立解决?

### 问题内容

按网上说的push到自己的库,但查看自己的库并没有这个文档

### 如果有截图，请提供一下

![屏幕截图 2023-10-18 191805](https://github.com/Peiyang-Aeromodelling-Association/demo-repository/assets/137747183/2ca886bb-2e90-4404-973d-321f3644b3ae)
![屏幕截图 2023-10-18 193834](https://github.com/Peiyang-Aeromodelling-Association/demo-repository/assets/137747183/0e3a48fd-723b-48bb-be47-
![屏幕截图 2023-10-18 195652](https://github.com/Peiyang-Aeromodelling-Association/demo-repository/assets/137747183/fc86a76f-0270-4798-95f7-fcb23b8854c8)
![屏幕截图 2023-10-18 195749](https://github.com/Peiyang-Aeromodelling-Association/demo-repository/assets/137747183/8f5ee01a-78ac-4adc-b3cf-f4ac7cf69f34)
d8f53019be6f)
![屏幕截图 2023-10-18 195627](https://github.com/Peiyang-Aeromodelling-Association/demo-repository/assets/137747183/86d81d6a-0290-4140-82d1-f40ad45d636a)

### 如果有报错信息，请提供一下

![屏幕截图 2023-10-18 193834](https://github.com/Peiyang-Aeromodelling-Association/demo-repository/assets/137747183/ca4c1036-7bdb-4ba8-9b8b-513728fa6bbd)

### 先前的尝试

以为是密钥的问题，看网上教程配了SSH密钥，结果还是不行。
按vscode里说的改一下 git push的话结果还不行，上网查，但是没有相关的错误

**Comment by luocfprime** [comment]
你clone的是小飞协的仓库还是你fork的仓库？

正确的操作是clone你fork的仓库。

查看方式：

```
git remote -v
```

另外，下次提问时把标题填好。

**Comment by victorycomrades** [comment]
我clone的是自己fork的仓库，但还是不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Peiyang-Aeromodelling-Association/demo-repository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月18日(星期三) 晚上8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Peiyang-Aeromodelling-Association/demo-repository] [Issue] (Issue #21)





 
你clone的是小飞协的仓库还是你fork的仓库？
 
正确的操作是clone你fork的仓库。
 
查看方式：
 git remote -v  
另外，下次提问时把标题填好。

**Comment by luocfprime** [comment]
以下命令结果粘贴过来：

```
git remote -v
```
```
ssh -T git@github.com
```
