### ISSUE TITLE
不知道push到哪里去了，没法完成PR操作

### ISSUE THREAD

**Issue by victorycomrades** [Peiyang-Aeromodelling-Association/demo-repository#24]
### 请确认你已经完成了以下检查

- [X] 有没有查找过以前类似的问题？
- [X] 有没有上网查过？
- [X] 有没有尝试独立解决?

### 问题内容

按网上操作不知道push到哪里去了，没法完成PR操作

### 如果有截图，请提供一下

![屏幕截图 2023-10-24 230802](https://github.com/Peiyang-Aeromodelling-Association/demo-repository/assets/137747183/9a6ee93a-3ab2-4f87-8638-90760ca1b5a8)
![屏幕截图 2023-10-24 231137](https://github.com/Peiyang-Aeromodelling-Association/demo-repository/assets/137747183/98978ea3-7079-4684-827b-8e063fad58d7)

### 先前的尝试

我跟着网上push到自己的fork库，但是我查看我的库里好像没有变，想PR也不行

**Comment by luocfprime** [comment]
我看你是尝试从一个名叫`65`的分支上合并。

![image](https://github.com/Peiyang-Aeromodelling-Association/demo-repository/assets/79003314/1a073da1-40b1-4bb8-aedb-b714d0c4c6ea)

确保如下事项：

1. 你clone时是从自己fork的仓库，而不是这个组织仓库。（可以通过`git remote -v`查看）
2. 我看你的仓库main和65分支都没有你的最新提交记录，所以确保你的新文件保存了（ctrl+s），然后是正确追踪了（git status查看，看看有没有红色`untracked`）
